### ISSUE TITLE
better-timestamp doesn't work with fluentd-0.14.12

### ISSUE THREAD

**Issue by chris060986** [shivaken/fluent-plugin-better-timestamp#1]
Outputfield cannot be added to fleuntd event:

`2017-02-06 11:23:15 +0100 [warn]: #0 emit transaction failed: error_class=RuntimeError error="BUG: use router.emit instead of Engine.emit" tag="fluent.info"
  2017-02-06 11:23:15 +0100 [warn]: #0 /var/lib/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/engine.rb:159:in `emit'
  2017-02-06 11:23:15 +0100 [warn]: #0 /var/lib/gems/2.1.0/gems/fluent-plugin-better-timestamp-0.1.0/lib/fluent/plugin/out_better_timestamp.rb:32:in `block in emit'
  2017-02-06 11:23:15 +0100 [warn]: #0 /var/lib/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/event.rb:107:in `call'
  2017-02-06 11:23:15 +0100 [warn]: #0 /var/lib/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/event.rb:107:in `each'
  2017-02-06 11:23:15 +0100 [warn]: #0 /var/lib/gems/2.1.0/gems/fluent-plugin-better-timestamp-0.1.0/lib/fluent/plugin/out_better_timestamp.rb:30:in `emit'
  2017-02-06 11:23:15 +0100 [warn]: #0 /var/lib/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/compat/output.rb:161:in `process'
  2017-02-06 11:23:15 +0100 [warn]: #0 /var/lib/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/plugin/output.rb:702:in `emit_sync'
  2017-02-06 11:23:15 +0100 [warn]: #0 /var/lib/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/event_router.rb:96:in `emit_stream'
  2017-02-06 11:23:15 +0100 [warn]: #0 /var/lib/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/event_router.rb:87:in `emit'
  2017-02-06 11:23:15 +0100 [warn]: #0 /var/lib/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/engine.rb:193:in `block in log_event_loop'
  2017-02-06 11:23:15 +0100 [warn]: #0 /var/lib/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/engine.rb:191:in `each'
  2017-02-06 11:23:15 +0100 [warn]: #0 /var/lib/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/engine.rb:191:in `log_event_loop'
2017-02-06 11:23:15 +0100 [error]: #0 failed to emit fluentd's log event tag="fluent.info" event={"worker"=>0, "message"=>"fluentd worker is now running worker=0"} error_class=RuntimeError error="BUG: use router.emit instead of `Engine.emit"`

**Comment by cosmo0920** [comment]
Fluentd v0.14 can use nanosecond precision time with `EventTime` msgpack ext type.
Could you paste entire config without sensitive information?
I suspect that this plugin is not useful in v0.14.

**Comment by chris060986** [comment]
Seems to be ok....

**Comment by cosmo0920** [comment]
This plugin cannot work with v0.14 due to: https://github.com/shivaken/fluent-plugin-better-timestamp/blob/master/lib/fluent/plugin/out_better_timestamp.rb#L32
